apiVersion: kaito.sh/v1alpha1
kind: RAGEngine
metadata:
  name: ragengine
spec:
  compute:
    instanceType: "Standard_NC96ads_A100_v4"  
    labelSelector:
      matchLabels:
        apps: ragengine
  embedding:  
    local:
      modelID: "BAAI/bge-small-en-v1.5"       
  inferenceService:  
    url: "http://<inference-url>/v1/chat/completions"
    contextWindowSize: 16000