apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air-web
spec:
  template:
    spec:
      containers:
      - name: contoso-air-web
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
