apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air-web
spec:
  template:
    spec:
      containers:
      - name: contoso-air-web
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
