apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contoso-air-prod

resources:
- ../../

namePrefix: prod-

commonLabels:
  environment: production

replicas:
- name: contoso-air-web
  count: 5

images:
- name: contoso-air
  newTag: stable

configMapGenerator:
- name: contoso-air-config
  literals:
  - NODE_ENV=production
  - PORT=3000
  behavior: replace

patchesStrategicMerge:
- deployment-patch.yaml
